# Generated by Django 4.1.2 on 2022-10-27 22:07

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.createModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, Serialize=False, Verbose_name='ID)),
                ('title', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('age', models.IntegerField()),
            ],
),
migrations.CreateModel(
    name='Song',
    fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, Serialize=False, Verbose_name='ID)),
                ('title', models.CharField(max_length=400)),
                ('date_released', models.DateField()),
                ('likes', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('artiste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=musicapps.artiste)),    
    ],
),
migrations.CreateModel(
    name='Lyric',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('content', models.TextField()),
        ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapps.song'))
    ]
)  